"use client";

import {
  FileText,
  Download,
  DollarSign,
  TrendingUp,
  TrendingDown,
  ArrowUpRight,
  ArrowDownRight,
  Printer,
  CheckCircle2,
  BarChart3,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { mockTaxSummary } from "@/lib/mock-data";

function formatCurrency(amount: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
  }).format(amount);
}

function SummaryRow({
  label,
  amount,
  indent = false,
  bold = false,
  green = false,
  red = false,
}: {
  label: string;
  amount: number;
  indent?: boolean;
  bold?: boolean;
  green?: boolean;
  red?: boolean;
}) {
  return (
    <div
      className={`flex justify-between py-2 ${indent ? "pl-6" : ""} ${
        bold ? "font-semibold border-t pt-3" : ""
      }`}
    >
      <span className={`text-sm ${indent ? "text-muted-foreground" : ""}`}>
        {label}
      </span>
      <span
        className={`text-sm font-medium ${
          green
            ? "text-[#38a169] dark:text-[#48bb78]"
            : red
              ? "text-red-600 dark:text-red-400"
              : ""
        }`}
      >
        {amount < 0 ? `(${formatCurrency(Math.abs(amount))})` : formatCurrency(amount)}
      </span>
    </div>
  );
}

export default function SummaryPage() {
  const s = mockTaxSummary;

  const handleExport = () => {
    const summaryText = `
TAX SUMMARY - ${s.taxYear}
========================
Filing Status: ${s.filingStatus}

INCOME
------
Wages: ${formatCurrency(s.income.wages)}
Self-Employment: ${formatCurrency(s.income.selfEmployment)}
Dividends: ${formatCurrency(s.income.dividends)}
Interest: ${formatCurrency(s.income.interest)}
Total Income: ${formatCurrency(s.income.totalIncome)}

ADJUSTMENTS
-----------
SE Tax Deduction: ${formatCurrency(s.adjustments.selfEmploymentTax)}
Health Insurance: ${formatCurrency(s.adjustments.healthInsurance)}
Total Adjustments: ${formatCurrency(s.adjustments.totalAdjustments)}

AGI: ${formatCurrency(s.agi)}

DEDUCTIONS (Itemized)
--------------------
Mortgage Interest: ${formatCurrency(s.deductions.mortgageInterest)}
SALT (capped): ${formatCurrency(s.deductions.saltCap)}
Charitable: ${formatCurrency(s.deductions.charitableContributions)}
Home Office: ${formatCurrency(s.deductions.homeOffice)}
Business Vehicle: ${formatCurrency(s.deductions.businessVehicle)}
QBI Deduction: ${formatCurrency(s.deductions.qbiDeduction)}
Total Itemized: ${formatCurrency(s.deductions.totalItemized)}

Taxable Income: ${formatCurrency(s.taxableIncome)}

TAX CALCULATION
--------------
Regular Tax: ${formatCurrency(s.taxCalculation.regularTax)}
SE Tax: ${formatCurrency(s.taxCalculation.selfEmploymentTax)}
Child Tax Credit: ${formatCurrency(s.taxCalculation.childTaxCredit)}
Child Care Credit: ${formatCurrency(s.taxCalculation.childCareCareCredit)}
Total Tax: ${formatCurrency(s.taxCalculation.totalTax)}

PAYMENTS
--------
Federal Withheld: ${formatCurrency(s.payments.federalWithheld)}
Estimated Payments: ${formatCurrency(s.payments.estimatedPayments)}
Total Payments: ${formatCurrency(s.payments.totalPayments)}

REFUND: ${formatCurrency(s.refundOrOwed)}
Effective Tax Rate: ${s.effectiveTaxRate}%
Marginal Tax Rate: ${s.marginalTaxRate}%

Generated by TaxIQ - For educational purposes only.
    `.trim();

    const blob = new Blob([summaryText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `TaxIQ_Summary_${s.taxYear}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="flex items-start justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold">Tax Summary</h1>
          <p className="text-muted-foreground mt-1">
            Your {s.taxYear} tax overview. Export this summary for your CPA
            or records.
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => window.print()}>
            <Printer className="mr-2 h-4 w-4" />
            Print
          </Button>
          <Button
            className="bg-[#38a169] hover:bg-[#2f855a] text-white"
            onClick={handleExport}
          >
            <Download className="mr-2 h-4 w-4" />
            Export
          </Button>
        </div>
      </div>

      {/* Overview Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="text-xs text-muted-foreground">Total Income</div>
            <div className="text-xl font-bold">
              {formatCurrency(s.income.totalIncome)}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="text-xs text-muted-foreground">Taxable Income</div>
            <div className="text-xl font-bold">
              {formatCurrency(s.taxableIncome)}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="text-xs text-muted-foreground">Total Tax</div>
            <div className="text-xl font-bold">
              {formatCurrency(s.taxCalculation.totalTax)}
            </div>
          </CardContent>
        </Card>
        <Card className="border-[#38a169]/30 dark:border-[#48bb78]/30 bg-[#38a169]/5 dark:bg-[#48bb78]/5">
          <CardContent className="pt-4 pb-4">
            <div className="text-xs text-muted-foreground">Refund</div>
            <div className="text-xl font-bold text-[#38a169] dark:text-[#48bb78]">
              {formatCurrency(s.refundOrOwed)}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Year over Year */}
      <Card className="mb-8">
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            <BarChart3 className="h-5 w-5" />
            Year-over-Year Comparison
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div>
              <div className="text-sm text-muted-foreground mb-1">
                Income Change
              </div>
              <div className="flex items-center gap-1">
                <ArrowUpRight className="h-4 w-4 text-[#38a169] dark:text-[#48bb78]" />
                <span className="text-lg font-bold">
                  {formatCurrency(
                    s.income.totalIncome - s.previousYear.totalIncome
                  )}
                </span>
              </div>
              <div className="text-xs text-[#38a169] dark:text-[#48bb78]">
                +
                {(
                  ((s.income.totalIncome - s.previousYear.totalIncome) /
                    s.previousYear.totalIncome) *
                  100
                ).toFixed(1)}
                % vs {s.taxYear - 1}
              </div>
            </div>
            <div>
              <div className="text-sm text-muted-foreground mb-1">
                Tax Change
              </div>
              <div className="flex items-center gap-1">
                <ArrowUpRight className="h-4 w-4 text-red-500" />
                <span className="text-lg font-bold">
                  {formatCurrency(
                    s.taxCalculation.totalTax - s.previousYear.totalTax
                  )}
                </span>
              </div>
              <div className="text-xs text-red-500">
                +
                {(
                  ((s.taxCalculation.totalTax - s.previousYear.totalTax) /
                    s.previousYear.totalTax) *
                  100
                ).toFixed(1)}
                % vs {s.taxYear - 1}
              </div>
            </div>
            <div>
              <div className="text-sm text-muted-foreground mb-1">
                Effective Rate
              </div>
              <div className="flex items-center gap-1">
                <ArrowDownRight className="h-4 w-4 text-[#38a169] dark:text-[#48bb78]" />
                <span className="text-lg font-bold">
                  {s.effectiveTaxRate}%
                </span>
              </div>
              <div className="text-xs text-[#38a169] dark:text-[#48bb78]">
                Down from {s.previousYear.effectiveRate}%
              </div>
            </div>
            <div>
              <div className="text-sm text-muted-foreground mb-1">
                Refund Change
              </div>
              <div className="flex items-center gap-1">
                <ArrowUpRight className="h-4 w-4 text-[#38a169] dark:text-[#48bb78]" />
                <span className="text-lg font-bold">
                  {formatCurrency(s.refundOrOwed)}
                </span>
              </div>
              <div className="text-xs text-[#38a169] dark:text-[#48bb78]">
                +{formatCurrency(s.refundOrOwed - s.previousYear.refund)} vs{" "}
                {s.taxYear - 1}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Detailed Summary */}
      <div className="grid lg:grid-cols-2 gap-6">
        {/* Income */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <DollarSign className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              Income
            </CardTitle>
          </CardHeader>
          <CardContent>
            <SummaryRow label="Wages (W-2)" amount={s.income.wages} indent />
            <SummaryRow
              label="Self-Employment"
              amount={s.income.selfEmployment}
              indent
            />
            <SummaryRow label="Dividends" amount={s.income.dividends} indent />
            <SummaryRow label="Interest" amount={s.income.interest} indent />
            <SummaryRow
              label="Total Income"
              amount={s.income.totalIncome}
              bold
            />
            <Separator className="my-3" />
            <SummaryRow
              label="SE Tax Deduction"
              amount={-s.adjustments.selfEmploymentTax}
              indent
            />
            <SummaryRow
              label="Health Insurance"
              amount={-s.adjustments.healthInsurance}
              indent
            />
            <SummaryRow
              label="Adjusted Gross Income"
              amount={s.agi}
              bold
            />
          </CardContent>
        </Card>

        {/* Deductions */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <TrendingDown className="h-5 w-5 text-green-600 dark:text-green-400" />
              Deductions
              <Badge className="bg-green-50 text-green-700 dark:bg-green-950/50 dark:text-green-400">
                Itemized
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <SummaryRow
              label="Mortgage Interest"
              amount={s.deductions.mortgageInterest}
              indent
            />
            <SummaryRow
              label="SALT (capped at $10K)"
              amount={s.deductions.saltCap}
              indent
            />
            <SummaryRow
              label="Charitable Contributions"
              amount={s.deductions.charitableContributions}
              indent
            />
            <SummaryRow
              label="Home Office"
              amount={s.deductions.homeOffice}
              indent
            />
            <SummaryRow
              label="Business Vehicle"
              amount={s.deductions.businessVehicle}
              indent
            />
            <SummaryRow
              label="QBI Deduction (20%)"
              amount={s.deductions.qbiDeduction}
              indent
            />
            <SummaryRow
              label="Total Itemized Deductions"
              amount={s.deductions.totalItemized}
              bold
              green
            />
            <div className="mt-2 text-xs text-muted-foreground">
              Standard deduction would be {formatCurrency(s.deductions.standardDeduction)}{" "}
              — itemizing saves you{" "}
              {formatCurrency(s.deductions.totalItemized - s.deductions.standardDeduction)}{" "}
              more
            </div>
          </CardContent>
        </Card>

        {/* Tax Calculation */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <FileText className="h-5 w-5 text-amber-600 dark:text-amber-400" />
              Tax Calculation
            </CardTitle>
          </CardHeader>
          <CardContent>
            <SummaryRow
              label="Taxable Income"
              amount={s.taxableIncome}
            />
            <Separator className="my-3" />
            <SummaryRow
              label="Regular Tax"
              amount={s.taxCalculation.regularTax}
              indent
            />
            <SummaryRow
              label="Self-Employment Tax"
              amount={s.taxCalculation.selfEmploymentTax}
              indent
            />
            <SummaryRow
              label="Child Tax Credit"
              amount={s.taxCalculation.childTaxCredit}
              indent
              green
            />
            <SummaryRow
              label="Child Care Credit"
              amount={s.taxCalculation.childCareCareCredit}
              indent
              green
            />
            <SummaryRow
              label="Total Tax"
              amount={s.taxCalculation.totalTax}
              bold
              red
            />
          </CardContent>
        </Card>

        {/* Payments & Refund */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-[#38a169] dark:text-[#48bb78]" />
              Payments & Refund
            </CardTitle>
          </CardHeader>
          <CardContent>
            <SummaryRow
              label="Federal Tax Withheld"
              amount={s.payments.federalWithheld}
              indent
            />
            <SummaryRow
              label="Estimated Payments"
              amount={s.payments.estimatedPayments}
              indent
            />
            <SummaryRow
              label="Total Payments"
              amount={s.payments.totalPayments}
              bold
            />
            <Separator className="my-3" />
            <SummaryRow
              label="Total Tax"
              amount={-s.taxCalculation.totalTax}
              indent
              red
            />
            <SummaryRow
              label="Total Payments"
              amount={s.payments.totalPayments}
              indent
            />
            <div className="flex justify-between py-3 border-t mt-2">
              <span className="text-lg font-bold">Estimated Refund</span>
              <span className="text-lg font-bold text-[#38a169] dark:text-[#48bb78]">
                {formatCurrency(s.refundOrOwed)}
              </span>
            </div>
            <div className="flex justify-between text-sm text-muted-foreground">
              <span>Effective Tax Rate</span>
              <span>{s.effectiveTaxRate}%</span>
            </div>
            <div className="flex justify-between text-sm text-muted-foreground">
              <span>Marginal Tax Rate</span>
              <span>{s.marginalTaxRate}%</span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Disclaimer */}
      <Card className="mt-8 border-[#1a365d]/20 dark:border-[#60a5fa]/20 bg-[#1a365d]/5 dark:bg-[#60a5fa]/5">
        <CardContent className="pt-6">
          <p className="text-sm text-muted-foreground">
            <strong>Important:</strong> This tax summary is for educational and
            planning purposes only. It is not a tax return and should not be
            filed with the IRS. Estimated amounts are based on the information
            you provided and may not reflect your actual tax liability. Consult
            a qualified tax professional for accurate tax preparation and
            filing.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
